#!/usr/share/ucs-test/runner python3
## desc: Create users/user with username which is already in use
## tags: [udm]
## roles: [domaincontroller_master]
## exposure: careful
## packages:
##   - univention-config
##   - univention-directory-manager-tools


import sys
import univention.testing.utils as utils
import univention.testing.udm as udm_test
import univention.testing.strings as uts

if __name__ == '__main__':
	with udm_test.UCSTestUDM() as udm:
		first_user_container = udm.create_object('container/cn', name=uts.random_name())
		second_user_container = udm.create_object('container/cn', name=uts.random_name())

		username = udm.create_user(position=first_user_container)[1]

		try:
			udm.create_user(username=username, position=second_user_container)
		except udm_test.UCSTestUDM_CreateUDMObjectFailed:
			sys.exit(0)

	utils.fail('Successfully created a user with a username which is already in use, which should not be possible')
